name: bosbase_app
description: A project showcasing a Flutter app following different platform IA conventions.
version: 1.0.0+1
 

environment:
  sdk: ^3.9.0-0

dependencies:
  english_words: ^4.0.0
  flutter_lorem: ^2.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  bosbase:
    git:
      url: https://github.com/bosbase/dart-sdk.git

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
